badges = ['github-actions/Test', 'metacpan']
module_maker = "ModuleBuild"
[build]
build_class = "builder::MyBuilder"
[no_index]
directory = ['t', 'xt', 'inc', 'share', 'eg', 'examples', 'author', 'builder', 'deps']
